@extends('admin.AdminLayout')

@section('content')
<div class="container py-5">

    <div class="card shadow-lg border-0 rounded-4 p-4 mb-4">
        <h2 class="text-center fw-bold mb-3">📊 Admin Sales Report</h2>
        <p class="text-center text-muted mb-4">
            Generated by <strong>{{ Auth::user()->name }}</strong> on {{ now()->format('F j, Y, g:i A') }}
        </p>

        <div class="row text-center mb-4">
            <div class="col-md-3 mb-3">
                <div class="card p-3 border-0 bg-success text-white rounded-4 shadow">
                    <h5>Total Sales</h5>
                    <h3>₦{{ number_format($totalSales, 2) }}</h3>
                </div>
            </div>
            <div class="col-md-3 mb-3">
                <div class="card p-3 border-0 bg-primary text-white rounded-4 shadow">
                    <h5>Total Orders</h5>
                    <h3>{{ $totalOrders }}</h3>
                </div>
            </div>
            <div class="col-md-3 mb-3">
                <div class="card p-3 border-0 bg-warning text-dark rounded-4 shadow">
                    <h5>Unique Customers</h5>
                    <h3>{{ $uniqueCustomers }}</h3>
                </div>
            </div>
            <div class="col-md-3 mb-3">
                <div class="card p-3 border-0 bg-danger text-white rounded-4 shadow">
                    <h5>Top Item</h5>
                    <h3>{{ $topItem ? $topItem->name : 'N/A' }}</h3>
                </div>
            </div>
        </div>

        <div class="d-flex justify-content-between align-items-center mb-4">
            <h4 class="fw-bold">Sales Analysis</h4>
            <button class="btn btn-dark" id="downloadReport">
                <i class="bi bi-download"></i> Download PDF
            </button>
        </div>

        <div class="row">
            <div class="col-md-6 mb-4">
                <canvas id="salesChart"></canvas>
            </div>
            <div class="col-md-6 mb-4">
                <canvas id="topItemsChart"></canvas>
            </div>
        </div>
    </div>

</div>

<!-- {{-- Pass dynamic data to JS --}}
<script>
    window.reportData = {
        months: @json($months),
        sales: @json($sales),
        topItems: @json($topItems),
        itemSales: @json($itemSales),
        date: "{{ now()->format('Y_m_d_H_i') }}"
    };
</script> -->

{{-- JS Libraries --}}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
<script src="{{ asset('assets/js/adminReport.js') }}"></script>
@endsection
